### ISSUE TITLE
Could you share the dataset?

### ISSUE THREAD

**Issue by kauttoj** [chongyangtao/IOI#1]
Thanks for the code guys. Could you also share the exact data that was used to obtain the results reported in the paper (i.e., train, dev, test sets and vocabulary)?

In the mean time, I experimented with the Ubuntu Corpus dataset (ver2) and got following not-so-good results for the development set. Probably did something wrong when preparing the data...

```
Dev results..........
('pred_scores: ', 500000)
Step: 66000 	| loss: 2.805 	| acc: 0.860 	|  2019-09-15 13:27:36
recall_2_1:  0.904
recall_at_1: 0.657
recall_at_2: 0.800
recall_at_5: 0.949
```

Also, I think there is a minor bug in the code "main.py" (line 220): Definitions of variables "minimal_val_step" and "minimal_val_loss" are missing.

**Comment by chongyangtao** [comment]
Hi, I have updated the readme and fixed the bug in "main.py" . You can prepare the data according to the instructions. Thanks~

**Comment by kauttoj** [comment]
Thanks. Now I used your data, although needed to train word2vec myself. However, the result was worse than before (after ~12h of training):

```
Dev results..........
('pred_scores: ', 500000)
Step: 38000 	| loss: 4.260 	| acc: 0.803 	|  2019-09-20 03:35:54
recall_2_1:  0.830
recall_at_1: 0.541
recall_at_2: 0.683
recall_at_5: 0.867
```

Maybe the default parameters aren't quite optimal. I'll do some additional testing.

**Comment by chongyangtao** [comment]
Hi, I provided the link of word2vec file in "download.sh".  You may adjust the LR strategy, which has a great impact on the performance of IOI.  In our experiment, we set decay_steps = 5000 when batch_size is 20.
