### ISSUE TITLE
Cannot download the data.

### ISSUE THREAD

**Issue by Coldog2333** [chongyangtao/IOI#2]
Hello, I am going to reproduce your paper of IOI, but I have a trouble in downloading the data. Could you please share the ubuntu_data and its word2vec model in other ways that are available for those who in China?

**Comment by BeyondSelves** [comment]
Hello, I have uploaded the dataset to Baidu Pan, please enjoy it: url:https://pan.baidu.com/s/1JUWtwwxQEO1EDT_6CE3NBw 
password:43ch

**Comment by Coldog2333** [comment]
Thank you for your kindly help!
